"""Added budget model

Revision ID: 080a920074fc
Revises: 4fa1ff0eb8f5
Create Date: 2024-03-04 00:15:11.511827
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080a920074fc'
down_revision = '4fa1ff0eb8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timeframe', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key('fk_budget_category', 'category', ['category_id'], ['id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('category_name')
        batch_op.drop_column('start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint('fk_budget_category', type_='foreignkey')
        batch_op.drop_column('timeframe')
        batch_op.drop_column('category_id')
    # ### end Alembic commands ###
